/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was automatically generated by informer-gen

package v1alpha1

import (
	time "time"

	dweller_v1alpha1 "github.com/fukt/dweller/pkg/apis/dweller/v1alpha1"
	versioned "github.com/fukt/dweller/pkg/client/clientset/versioned"
	internalinterfaces "github.com/fukt/dweller/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/fukt/dweller/pkg/client/listers/dweller/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// VaultSecretClaimInformer provides access to a shared informer and lister for
// VaultSecretClaims.
type VaultSecretClaimInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.VaultSecretClaimLister
}

type vaultSecretClaimInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewVaultSecretClaimInformer constructs a new informer for VaultSecretClaim type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewVaultSecretClaimInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredVaultSecretClaimInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredVaultSecretClaimInformer constructs a new informer for VaultSecretClaim type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredVaultSecretClaimInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DwellerV1alpha1().VaultSecretClaims(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DwellerV1alpha1().VaultSecretClaims(namespace).Watch(options)
			},
		},
		&dweller_v1alpha1.VaultSecretClaim{},
		resyncPeriod,
		indexers,
	)
}

func (f *vaultSecretClaimInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredVaultSecretClaimInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *vaultSecretClaimInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&dweller_v1alpha1.VaultSecretClaim{}, f.defaultInformer)
}

func (f *vaultSecretClaimInformer) Lister() v1alpha1.VaultSecretClaimLister {
	return v1alpha1.NewVaultSecretClaimLister(f.Informer().GetIndexer())
}
